otel_sdk:
    resource:
        attributes:
            service.name: "OtelBundle Demo app"

    trace:
        sampler: always_on
        span:
            processors: simple
        exporters:
            - jaeger+http://127.0.0.1:9412/api/v2/spans
            - zipkin+http://127.0.0.1:9411/api/v2/spans
