version: "3.7"

services:

  php:
    image: otel-demo-app 
    build: .
    volumes:
      - .:/app
    working_dir: /app 
    entrypoint: [ "bash", "/docker-entrypoint.sh" ]
    command: [ "php", "-S", "0.0.0.0:8080", "-t", "public" ]
    ports:
      - "8080:8080"
    
  js-watch:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    entrypoint: [""]
    command: "bash -c 'yarn install && yarn run watch'"

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9412
    ports:
      - 9412:9412
      - 16686:16686
